apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml

namespace: dev

bases:
  - ../../base

patchesStrategicMerge:
- patch/api-depl.yaml

images:
- name: myapp
  newName: anhmhtera/media-fe
  newTag: v0.1.3