apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml

namespace: dev

bases:
  - ../../base

patchesStrategicMerge:
- patch/api-depl.yaml

images:
- name: myapp
  newName: 905418455152.dkr.ecr.ap-southeast-1.amazonaws.com/sppl-app
  newTag: version-1.0.69