apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml

namespace: dev

bases:
  - ../../base

patchesStrategicMerge:
- patch/api-depl.yaml

images:
- name: myapp
  newName: image-registry.openshift-image-registry.svc:5000/openshift/httpd
  newTag: latest