apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml

namespace: dev

bases:
  - ../../base

#components:
#  - ../../components/external_db
#  - ../../components/cache