apiVersion: v1
kind: Service
metadata:
  labels:
    app: nginx-api
  name: nginx-api
  namespace: test
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: nginx-api
  type: NodePort
status:
  loadBalancer: {}
